name: Publish NuGet Packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Clean up build files (before)
        run: |
          $excluded_dirs = @("packages", "tests", "Cyrus.DB", ".vs", ".github")
          Get-ChildItem -Directory | ForEach-Object {
            if ($excluded_dirs -notcontains $_.Name) {
              Remove-Item -Recurse -Force -ErrorAction Ignore "$($_.FullName)\bin"
              Remove-Item -Recurse -Force -ErrorAction Ignore "$($_.FullName)\obj"
            }
          }

      - name: Restore dependencies
        run: |
          $projects = Get-ChildItem -Recurse -Filter *.csproj
          foreach ($project in $projects) {
            dotnet restore $project.FullName
          }

      - name: Build and pack NuGet packages
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          $excluded_dirs = @("packages", "tests", "Cyrus.DB", ".vs", ".github")
          $projects = Get-ChildItem -Recurse -Filter *.csproj
          foreach ($project in $projects) {
            dotnet build $project.FullName -c Release
            dotnet pack $project.FullName -c Release --output ./bin/Release
            $nupkgFiles = Get-ChildItem -Path "./bin/Release" -Filter '*.nupkg'
            foreach ($nupkgFile in $nupkgFiles) {
              dotnet nuget push "$($nupkgFile.FullName)" -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
            }
          }

      - name: Clean up build files (after)
        run: |
          $excluded_dirs = @("packages", "tests", "Cyrus.DB", ".vs", ".github")
          foreach ($dir in Get-ChildItem -Directory) {
            if ($excluded_dirs -notcontains $dir.Name) {
              Remove-Item -Recurse -Force -ErrorAction Ignore "$($dir.FullName)\bin"
              Remove-Item -Recurse -Force -ErrorAction Ignore "$($dir.FullName)\obj"
            }
          }
